from voluptuous import ALLOW_EXTRA, Schema, Boolean, Any

orders_history_with_monolith = Schema(
    {
        "data": [
            {
                "number": str,
                "id": int,
                "ordered_at": str,
                "status": Any(
                    "confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered", "refunded"
                ),
                "status_for_customer": str,
                "customer_first_name": str,
                "customer_last_name": str,
                "customer_email": str,
                "customer_phone": str,
                "items_count": int,
                "items_qty": int,
                "items_sum": int,
                "discount_amount": int,
                "calculated_total": int,
                "shipping_name": Any(None, str),
                "shipping_method_external": Any(
                    "delivery",
                    "pickup",
                    "delivery_service",
                    "post",
                    "delivery_service_economy",
                    "delivery_service_plus",
                    "delivery_service_same_day",
                    "pickup_economy",
                    "pickup_plus",
                    "pickup_same_day",
                    "post_economy",
                    "omni",
                    "reserveinstore",
                    "pickupinstore",
                    "shop_",
                    None,
                ),
                "delivery_price": int,
                "services": Any([str], None),
                "date": Any(str, None),
                "address": Any(str, None),
                "payment_method": Any("cash", "card", "raiffeisen", "podeli", "sbp", "sber", "payture"),
                "meta": {
                    "shippingMethods": {
                        "pickup": "пункт выдачи",
                        "delivery_service": "курьером",
                        "delivery": "курьером",
                        "post": "почта россии",
                        "delivery_service_economy": "курьером без примерки",
                        "delivery_service_plus": "курьером с примеркой",
                        "delivery_service_same_day": "курьером",
                        "pickup_economy": "в пункт выдачи",
                        "pickup_plus": "в пункт выдачи с примеркой",
                        "pickup_same_day": "в пункт выдачи",
                        "post_economy": "почтой россии",
                        "omni": "самовывоз из магазина",
                        "reserveinstore": "самовывоз из магазина",
                        "pickupinstore": "магазин",
                    },
                    "paymentMethods": {
                        "cash": "при получении",
                        "card": "онлайн",
                        "raiffeisen": "по Qr-коду",
                        "podeli": "подели — оплата по частям",
                        "payture": "онлайн",
                        "sbp": "по Qr-коду",
                    },
                },
                "items": [
                    {
                        "name": str,
                        "qty": int,
                        "price": int,
                        "final_price": int,
                        "discount_percent": int,
                        "variation_id": int,
                        "product_id": int,
                        "sku": str,
                        "picture": Any(str, None),
                        "article": Any(None, str),
                        "color": {"id": Any(int, None), "value": Any(None, str), "colorCode": Any(int, None)},
                        "size": {"id": Any(int, None), "value": Any(None, str)},
                        "height": {"id": Any(int, None), "value": Any(str, None)},
                        "category": {"id": Any(int, None), "name": Any(str, None)},
                        "gender": Any("female", "male", None),
                        "canceled": Boolean(),
                    }
                ],
            }
        ]
    },
    extra=ALLOW_EXTRA,
    required=True,
)

order_history = Schema(
    {
        "data": [
            {
                "number": str,
                "id": int,
                "ordered_at": str,
                "status": Any("confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered",
                              "refunded"),
                "status_for_customer": str,
                "customer_first_name": str,
                "customer_last_name": str,
                "customer_email": str,
                "customer_phone": str,
                "items_count": int,
                "items_qty": int,
                "items_sum": int,
                "discount_amount": int,
                "calculated_total": int,
                "shipping_name": Any(str, None),
                # убрать null
                "shipping_method_external": Any(
                    "delivery",
                    "pickup",
                    "reserveinstore",
                    "pickupinstore",
                    None
                ),
                "delivery_price": int,
                "services": Any([str], None),
                # убрать null
                "date": Any(str, None),
                "address": Any(str, None),
                # убрать null
                "payment_method": Any("cash", "podeli", "payture", "sbp", "sber"),
                "meta": {
                    "shippingMethods": {
                        "pickup": "пункт выдачи",
                        "delivery": "курьером",
                        "reserveinstore": "самовывоз из магазина",
                        "pickupinstore": "магазин",
                    },
                    "paymentMethods": {
                        "cash": "при получении",
                        "podeli": "подели — оплата по частям",
                        "payture": "онлайн",
                        "sber": "онлайн",
                        "sbp": "по Qr-коду",
                    },
                },
                "items": [
                    {
                        "name": str,
                        "qty": int,
                        "price": int,
                        "final_price": int,
                        "discount_percent": int,
                        "variation_id": int,
                        "product_id": int,
                        "sku": str,
                        "picture": str,
                        "article": str,
                        "color": {"id": int, "value": str, "colorCode": int},
                        "size": {"id": int, "value": str},
                        "height": {"id": Any(int,None), "value": Any(str,None)},
                        "category": {"id": int, "name": str},
                        "gender": Any("female", "male"),
                        "canceled": Boolean(),
                    }
                ],
            }
        ]
    },
    extra=ALLOW_EXTRA,
    required=True,
)

order_cash_pickup = Schema(
    {
        "data": {
            "id": int,
            "number": str,
            "status": Any("confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered", "refunded"),
            "customer": {"email": str, "phone": str, "firstName": str, "lastName": str},
            "shipping": {
                "method": {
                    "name": "в пункт выдачи",
                    "value": "pickup",
                },
                "name": str,
                "pickPointAddress": str,
                "workingHours": str,
                "subwayStation": Any(str, None),
                "maxWaitingDays": int,
                "from": None,
                "to": None,
                "date": str,
                "address": None,
                "intervalId": None,
                "pickpointId": str,
                "storeId": None,
                "storeExternalId": str,
                "deliveryPrice": int,
                "services": Any([str], None),
            },
            "payment": {
                "method": {
                    "name": "при получении",
                    "value": "cash",
                }
            },
            "promocode": Any(None, {"value": str, "applied": Boolean}),
            "frontendData": None,
            "autoconfirmEnable": Boolean(),
            "autoconfirm": Boolean(),
            "maxAvailableQty": int,
            "leftToTreshold": int,
            "discount": Any(None, {"total": int}),
            "items": [
                {
                    "id": int,
                    "sku": str,
                    "name": str,
                    "qty": int,
                    "maximumPrice": int,
                    "calculatedPrice": int,
                    "maximumSum": int,
                    "calculatedSum": int,
                    "discountPercent": int,
                    "discountAmount": int,
                    "picture": str,
                    "article": str,
                    "productId": int,
                    "color": {"id": int, "value": str, "colorCode": int},
                    "size": {"id": int, "value": str},
                    "height": Any(None, {"id": int, "value": str}),
                    "category": {"id": int, "name": str},
                    "gender": Any("female", "male"),
                    "isEmployeeDiscountApplied": Boolean(),
                }
            ],
            "itemsCount": int,
            "itemsQty": int,
            "maximumTotal": int,
            "calculatedTotal": int,
            "resultTotal": int,
        },
        "status": "ok",
    },
    extra=ALLOW_EXTRA,
    required=True,
)

order_podeli_reserveinstore = Schema(
    {
        "data": {
            "id": int,
            "number": str,
            "status": Any("confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered", "refunded"),
            "customer": {"email": str, "phone": str, "firstName": str, "lastName": str},
            "shipping": {
                "method": {"name": "из магазина", "value": "reserveinstore"},
                "name": str,
                "pickPointAddress": str,
                "workingHours": str,
                "subwayStation": Any(str, None),
                "maxWaitingDays": int,
                "from": None,
                "to": None,
                "date": str,
                "address": None,
                "intervalId": None,
                "pickpointId": None,
                "storeId": int,
                "storeExternalId": str,
                "deliveryPrice": int,
                "services": Any([str], None),
            },
            "payment": {"method": {"name": "подели - оплата по частям", "value": "podeli"}},
            "promocode": Any(None, {"value": str, "applied": Boolean}),
            "frontendData": None,
            "autoconfirmEnable": Boolean,
            "autoconfirm": Boolean,
            "maxAvailableQty": int,
            "leftToTreshold": int,
            "discount": Any(None, {"total": int}),
            "items": [
                {
                    "id": int,
                    "sku": str,
                    "name": str,
                    "qty": int,
                    "maximumPrice": int,
                    "calculatedPrice": int,
                    "maximumSum": int,
                    "calculatedSum": int,
                    "discountPercent": int,
                    "discountAmount": int,
                    "picture": str,
                    "article": str,
                    "productId": int,
                    "color": {"id": int, "value": str, "colorCode": int},
                    "size": {"id": int, "value": str},
                    "height": Any({"id": int, "value": str}, None),
                    "category": {"id": int, "name": str},
                    "gender": Any("female", "male"),
                    "isEmployeeDiscountApplied": Boolean,
                },
            ],
            "itemsCount": int,
            "itemsQty": int,
            "maximumTotal": int,
            "calculatedTotal": int,
            "resultTotal": int,
        },
        "status": "ok",
    },
    extra=ALLOW_EXTRA,
    required=True,
)

order_sbp_omni2 = Schema(
    {
        "data": {
            "id": int,
            "number": str,
            "status": Any("confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered", "refunded"),
            "customer": {"email": str, "phone": str, "firstName": str, "lastName": str},
            "shipping": {
                "method": {
                    "name": "в пункт выдачи",
                    "value": "pickup",
                },
                "name": str,
                "pickPointAddress": str,
                "workingHours": str,
                "subwayStation": Any(str, None),
                "maxWaitingDays": int,
                "from": None,
                "to": None,
                "date": str,
                "address": None,
                "intervalId": None,
                "pickpointId": str,
                "storeId": None,
                "storeExternalId": str,
                "deliveryPrice": int,
                "services": Any([str], None),
            },
            "payment": {
                "method": {
                    "name": "при получении",
                    "value": "cash",
                }
            },
            "promocode": Any(None, {"value": str, "applied": Boolean}),
            "frontendData": None,
            "autoconfirmEnable": Boolean(),
            "autoconfirm": Boolean(),
            "maxAvailableQty": int,
            "leftToTreshold": int,
            "discount": Any(None, {"total": int}),
            "items": [
                {
                    "id": int,
                    "sku": str,
                    "name": str,
                    "qty": int,
                    "maximumPrice": int,
                    "calculatedPrice": int,
                    "maximumSum": int,
                    "calculatedSum": int,
                    "discountPercent": int,
                    "discountAmount": int,
                    "picture": str,
                    "article": str,
                    "productId": int,
                    "color": {"id": int, "value": str, "colorCode": int},
                    "size": {"id": int, "value": str},
                    "height": Any(None, {"id": int, "value": str}),
                    "category": {"id": int, "name": str},
                    "gender": Any("female", "male"),
                    "isEmployeeDiscountApplied": Boolean(),
                }
            ],
            "itemsCount": int,
            "itemsQty": int,
            "maximumTotal": int,
            "calculatedTotal": int,
            "resultTotal": int,
        },
        "status": "ok",
    },
    extra=ALLOW_EXTRA,
    required=True,
)

order_sbp_pickupinstore = Schema(
    {
        "data": {
            "id": int,
            "number": str,
            "status": Any("confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered", "refunded"),
            "customer": {"email": str, "phone": str, "firstName": str, "lastName": str},
            "shipping": {
                "method": {"name": "в магазин", "value": "pickupinstore"},
                "name": str,
                "pickPointAddress": str,
                "workingHours": str,
                "subwayStation": None,
                "maxWaitingDays": int,
                "from": None,
                "to": None,
                "date": str,
                "address": None,
                "intervalId": None,
                "pickpointId": None,
                "storeId": int,
                "storeExternalId": str,
                "deliveryPrice": int,
                "services": Any([str], None),
            },
            "payment": {"method": {"name": "система быстрых платежей", "value": "sbp"}},
            "promocode": Any(None, {"value": str, "applied": Boolean}),
            "frontendData": None,
            "autoconfirmEnable": Boolean,
            "autoconfirm": Boolean,
            "maxAvailableQty": int,
            "leftToTreshold": int,
            "discount": Any(None, {"total": int}),
            "items": [
                {
                    "id": int,
                    "sku": str,
                    "name": str,
                    "qty": int,
                    "maximumPrice": int,
                    "calculatedPrice": int,
                    "maximumSum": int,
                    "calculatedSum": int,
                    "discountPercent": int,
                    "discountAmount": int,
                    "picture": str,
                    "article": str,
                    "productId": int,
                    "color": {"id": int, "value": str, "colorCode": int},
                    "size": {"id": int, "value": str},
                    "height": Any({"id": int, "value": str}, None),
                    "category": {"id": int, "name": str},
                    "gender": "female",
                    "isEmployeeDiscountApplied": Boolean,
                }
            ],
            "itemsCount": int,
            "itemsQty": int,
            "maximumTotal": int,
            "calculatedTotal": int,
            "resultTotal": int,
        },
        "status": "ok",
    },
    extra=ALLOW_EXTRA,
    required=True,
)

order_sber_delivery = Schema(
    {
        "data": {
            "id": int,
            "number": str,
            "status": Any("confirmed", "picked", "canceled", "on_delivery", "pickup_ready", "delivered", "refunded"),
            "customer": {"email": str, "phone": str, "firstName": str, "lastName": str},
            "shipping": {
                "method": {"name": "курьером", "value": "delivery"},
                "name": None,
                "pickPointAddress": None,
                "workingHours": None,
                "subwayStation": None,
                "maxWaitingDays": None,
                "from": str,
                "to": str,
                "date": str,
                "address": {
                    "streetName": str,
                    "streetFiasId": str,
                    "building": str,
                    "buildingFiasId": str,
                    "roomNumber": Any(None, str),
                    "entrance": Any(None, str),
                    "floor": Any(None, str),
                    "interphone": Any(None, str),
                    "zipcode": Any(None, str),
                },
                "intervalId": str,
                "pickpointId": None,
                "storeId": None,
                "storeExternalId": None,
                "deliveryPrice": int,
                "services": Any([str], None),
            },
            "payment": {"method": {"name": "онлайн", "value": "sber"}},
            "promocode": Any(None, {"value": str, "applied": Boolean}),
            "frontendData": None,
            "autoconfirmEnable": Boolean,
            "autoconfirm": Boolean,
            "maxAvailableQty": int,
            "leftToTreshold": int,
            "discount": Any(None, {"total": int}),
            "items": [
                {
                    "id": int,
                    "sku": str,
                    "name": str,
                    "qty": int,
                    "maximumPrice": int,
                    "calculatedPrice": int,
                    "maximumSum": int,
                    "calculatedSum": int,
                    "discountPercent": int,
                    "discountAmount": int,
                    "picture": str,
                    "article": str,
                    "productId": int,
                    "color": {"id": int, "value": str, "colorCode": int},
                    "size": {"id": int, "value": str},
                    "height": Any({"id": int, "value": str}, None),
                    "category": {"id": int, "name": str},
                    "gender": Any("female", "male"),
                    "isEmployeeDiscountApplied": Boolean,
                }
            ],
            "itemsCount": int,
            "itemsQty": int,
            "maximumTotal": int,
            "calculatedTotal": int,
            "resultTotal": int,
        },
        "status": "ok",
    },
    extra=ALLOW_EXTRA,
    required=True,
)
